# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.57704571 0.26007116 0.3675412  0.5217313  0.71870494]
  [0.1847141  0.20281165 0.40119255 0.63949922 0.23847502]
  [0.1991583  0.32396296 0.00876982 0.65658832 0.3993103 ]]

 [[0.85151424 0.66291788 0.98021279 0.93330771 0.46548922]
  [0.05911844 0.66944317 0.11412149 0.22804996 0.02599203]
  [0.00871191 0.97947672 0.05192693 0.09779126 0.55983658]]]


In [8]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[6.26965507e-01 1.22309221e-01 6.93607463e-01 8.19283698e-01
   5.15655588e-01]
  [6.13629451e-01 8.09308576e-01 5.80108726e-01 6.55751444e-01
   1.11489825e-01]
  [6.64867273e-01 4.29052804e-01 6.06415636e-04 2.76403437e-01
   1.11698062e-01]]

 [[7.48051154e-01 8.19087504e-02 8.62540212e-01 2.81918327e-01
   9.39365543e-01]
  [8.80370023e-01 8.14530478e-01 5.05444884e-01 8.61748180e-01
   1.37040567e-02]
  [6.91893348e-01 8.30648825e-01 6.87737317e-01 6.05651312e-01
   4.68175067e-01]]]


In [16]:
# Method 3
a = np.random.randn(2,3,5)


#### 4. Print *a*.


In [17]:
# your code here
print(a)

[[[ 0.15029962  0.16709118 -1.81006912 -1.07990635  0.26090639]
  [-0.39069937 -0.22648089 -0.05553226  0.07993998  0.26112052]
  [-1.09173696  0.10820165 -1.44217709 -0.59204743  0.05324294]]

 [[ 0.59013886  0.53156329  0.83228162  1.71264247 -1.3698096 ]
  [-0.72437669  0.37578938  0.59568654 -0.43701517  2.5370072 ]
  [ 0.56318257  0.7255606  -0.71467409 -0.15693535 -0.92157976]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
print(a.shape)
print(a.size)

print(b.shape)
print(b.size)

#It seems like they are the same size 
print(a.size == b.size)


(2, 3, 5)
30
(5, 2, 3)
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
# No, because they are of different dimensions 
print(a.shape == b.shape)

False


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c = np.reshape(b, (2,3,5))
print(c.shape)
print(c)

(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
# The arrays need to be the same dimensions
d = np.add(a,c)
print(d)


[[[ 1.15029962  1.16709118 -0.81006912 -0.07990635  1.26090639]
  [ 0.60930063  0.77351911  0.94446774  1.07993998  1.26112052]
  [-0.09173696  1.10820165 -0.44217709  0.40795257  1.05324294]]

 [[ 1.59013886  1.53156329  1.83228162  2.71264247 -0.3698096 ]
  [ 0.27562331  1.37578938  1.59568654  0.56298483  3.5370072 ]
  [ 1.56318257  1.7255606   0.28532591  0.84306465  0.07842024]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# your code/answer here
print(a)

print(d)
# for some/most values, you are adding by 1

[[[ 0.15029962  0.16709118 -1.81006912 -1.07990635  0.26090639]
  [-0.39069937 -0.22648089 -0.05553226  0.07993998  0.26112052]
  [-1.09173696  0.10820165 -1.44217709 -0.59204743  0.05324294]]

 [[ 0.59013886  0.53156329  0.83228162  1.71264247 -1.3698096 ]
  [-0.72437669  0.37578938  0.59568654 -0.43701517  2.5370072 ]
  [ 0.56318257  0.7255606  -0.71467409 -0.15693535 -0.92157976]]]
[[[ 1.15029962  1.16709118 -0.81006912 -0.07990635  1.26090639]
  [ 0.60930063  0.77351911  0.94446774  1.07993998  1.26112052]
  [-0.09173696  1.10820165 -0.44217709  0.40795257  1.05324294]]

 [[ 1.59013886  1.53156329  1.83228162  2.71264247 -0.3698096 ]
  [ 0.27562331  1.37578938  1.59568654  0.56298483  3.5370072 ]
  [ 1.56318257  1.7255606   0.28532591  0.84306465  0.07842024]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
e = np.multiply(a, c)
print(e)

[[[ 0.15029962  0.16709118 -1.81006912 -1.07990635  0.26090639]
  [-0.39069937 -0.22648089 -0.05553226  0.07993998  0.26112052]
  [-1.09173696  0.10820165 -1.44217709 -0.59204743  0.05324294]]

 [[ 0.59013886  0.53156329  0.83228162  1.71264247 -1.3698096 ]
  [-0.72437669  0.37578938  0.59568654 -0.43701517  2.5370072 ]
  [ 0.56318257  0.7255606  -0.71467409 -0.15693535 -0.92157976]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [34]:
# your code/answer here
#Equal in what sense? Size? Shape?
# They appear to equal in shape size and values. 
print(a==e)

print(a.shape)
print(a.size)

print(e.shape)
print(e.size)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
(2, 3, 5)
30
(2, 3, 5)
30


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
# your code here
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = np.mean(d)
print(d_mean)

3.5370072026778927
-0.8100691223476884
0.951053822715017


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [38]:
# your code here
f = np.empty([2,3,5])
print(f)


[[[0.15029962 0.16709118 1.81006912 1.07990635 0.26090639]
  [0.39069937 0.22648089 0.05553226 0.07993998 0.26112052]
  [1.09173696 0.10820165 1.44217709 0.59204743 0.05324294]]

 [[0.59013886 0.53156329 0.83228162 1.71264247 1.3698096 ]
  [0.72437669 0.37578938 0.59568654 0.43701517 2.5370072 ]
  [0.56318257 0.7255606  0.71467409 0.15693535 0.92157976]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [57]:
# your code here


ind1=0
ind2=0
ind3=0

for i in d: 
    for j in i: 
        for k in j: 
            if k == d_mean:
                f[ind1][ind2][ind3] = 50 
            elif k == d_min:
                f[ind1][ind2][ind3] = 0
            elif k == d_max:
                f[ind1][ind2][ind3] = 100
            elif (k > d_min) and (k < d_mean):
                f[ind1][ind2][ind3] = 25
            elif (k > d_mean) and (k < d_max):
                f[ind1][ind2][ind3] = 75 
            ind3 += 1
        ind3=0
        ind2+=1
    ind2=0
    ind1+=1

print(f)  

[[[ 75.  75.   0.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  25. 100.]
  [ 75.  75.  25.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [58]:
# your code here

print(d)
print(f)

[[[ 1.15029962  1.16709118 -0.81006912 -0.07990635  1.26090639]
  [ 0.60930063  0.77351911  0.94446774  1.07993998  1.26112052]
  [-0.09173696  1.10820165 -0.44217709  0.40795257  1.05324294]]

 [[ 1.59013886  1.53156329  1.83228162  2.71264247 -0.3698096 ]
  [ 0.27562331  1.37578938  1.59568654  0.56298483  3.5370072 ]
  [ 1.56318257  1.7255606   0.28532591  0.84306465  0.07842024]]]
[[[ 75.  75.   0.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  25. 100.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [61]:
# your code here


ind1=0
ind2=0
ind3=0

for i in d: 
    for j in i: 
        for k in j: 
            if k == d_mean:
                f[ind1][ind2][ind3] = str('C') 
            elif k == d_min:
                f[ind1][ind2][ind3] = str('A')
            elif k == d_max:
                f[ind1][ind2][ind3] = str('E')
            elif (k > d_min) and (k < d_mean):
                f[ind1][ind2][ind3] = str('B')
            elif (k > d_mean) and (k < d_max):
                f[ind1][ind2][ind3] = str('D')
            ind3 += 1
        ind3=0
        ind2+=1
    ind2=0
    ind1+=1

print(f) 

ValueError: could not convert string to float: 'D'